name: clinical_os_manager
description: Smart Maintenance App - Gerenciamento inteligente de manutenções e equipamentos.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  # Navigation
  go_router: ^14.6.2

  # Network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Local Storage
  shared_preferences: ^2.3.2

  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  gap: ^3.0.1

  # Utils
  intl: ^0.19.0
  logger: ^2.4.0
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.7.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts: []
